// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "e7fdc212-8115-4bbb-8d68-33abb81d1508";

const char SSID[]               = "Broker_WiFi";    // Network SSID (name)
const char PASS[]               = "EightChars";    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = "REgguJ5V2Qo5jXJ1XXlgJJf3G";    // Secret device password

void onMotorPinChange();
void onWaterPumpChange();

CloudTemperatureSensor temperature_cool;
CloudTemperatureSensor temperature_hot;
CloudRelativeHumidity humidity_cool;
CloudRelativeHumidity humidity_hot;
bool motorPin;
bool waterPump;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(temperature_hot, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(humidity_cool, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(humidity_hot, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(motorPin, READWRITE, ON_CHANGE, onMotorPinChange);
  ArduinoCloud.addProperty(waterPump, READWRITE, ON_CHANGE, onWaterPumpChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
